services:
    redis:
        image: redis:8.0-alpine
        container_name: redis
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - 6300:6379
        volumes:
            - redis_data:/data

    postgres:
        container_name: postgres
        image: postgres:17.5-alpine
        restart: always
        ports:
            - "5400:5432"
        environment:
            POSTGRES_DB: auth_saas
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    redis_data:
    pgdata:
